/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AjudaRouteImport } from './routes/ajuda'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as MonitoramentoRouteImport } from './routes/monitoramento'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AjudaRoute = AjudaRouteImport.update({
  id: '/ajuda',
  path: '/ajuda',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoramentoRoute = MonitoramentoRouteImport.update({
  id: '/monitoramento',
  path: '/monitoramento',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ajuda': typeof AjudaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/historico': typeof HistoricoRoute
  '/monitoramento': typeof MonitoramentoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ajuda': typeof AjudaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/historico': typeof HistoricoRoute
  '/monitoramento': typeof MonitoramentoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ajuda': typeof AjudaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/historico': typeof HistoricoRoute
  '/monitoramento': typeof MonitoramentoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ajuda' | '/configuracoes' | '/historico' | '/monitoramento'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ajuda' | '/configuracoes' | '/historico' | '/monitoramento'
  id:
    | '__root__'
    | '/'
    | '/ajuda'
    | '/configuracoes'
    | '/historico'
    | '/monitoramento'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AjudaRoute: typeof AjudaRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  HistoricoRoute: typeof HistoricoRoute
  MonitoramentoRoute: typeof MonitoramentoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajuda': {
      id: '/ajuda'
      path: '/ajuda'
      fullPath: '/ajuda'
      preLoaderRoute: typeof AjudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoramento': {
      id: '/monitoramento'
      path: '/monitoramento'
      fullPath: '/monitoramento'
      preLoaderRoute: typeof MonitoramentoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AjudaRoute: AjudaRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  HistoricoRoute: HistoricoRoute,
  MonitoramentoRoute: MonitoramentoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
